# Generated by Django 2.2.4 on 2019-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField()),
            ],
        ),
    ]
