# Generated by Django 2.2.4 on 2019-11-24 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 24, 16, 30, 21, 613258)),
        ),
    ]
